### ISSUE TITLE
Pathogen incompatibility due to folder name

### ISSUE THREAD

**Issue by Cisplatin** [gregsexton/MatchTag#34]
Pathogen only finds plugins if the `.vim` files are in a folder called `plugin`. Because it's called `ftplugin` instead, pathogen doesn't not automatically install the plugin.

If there's no reason to call it `ftplugin`, changing it to `plugin` would decrease friction for users.

**Comment by gregsexton** [comment]
Are you sure this is true? I have plenty of plugins using pathogen that have an ftplugin component.

**Comment by Cisplatin** [comment]
I've tested it on both mine and my friends' Mac, using vim 7.4, and the latest version of pathogen (undefined?).

Seems like it affects other people as well, judging by the second answer of http://stackoverflow.com/questions/3383502/pathogen-does-not-load-plugins

**Comment by Laranjadinho** [comment]
@Cisplatin @gregsexton I have the same problem here. I had to rename `ftplugin` directories to `plugin` (which is not a good thing to do).

**Comment by gishmel** [comment]
I would agree with @Laranjadinho that this is definitely not a problem with the plugin but in this case by the plugin manager. Doesn't make sense to merge this in as its directly against the purpose of the filetype features in vim.
