### ISSUE TITLE
Plugin failure

### ISSUE THREAD

**Issue by chan15** [gregsexton/MatchTag#40]
vim: 8.1.173
plugin: latest

function <SNR>109_Highlight_Matching_Pair[20]..<SNR>109_SearchForMatchingTag

E475: incorrect variable: 0

**Comment by markmoser** [comment]
I'm seeing this too. Seems to be choking on `"` double quotes

MacVim: 8.1.235

**Comment by chan15** [comment]
it seems the author won't take care of this project anymore, any suggestion for another plugin?

**Comment by jeromefaria** [comment]
Same here. Updated all plugins and MacVim to 8.1.235 yesterday and now running into this issue:
```
Error detected while processing function <SNR>212_Highlight_Matching_Pair[20]..<SNR>212_SearchForMatchingTag:
```

I would also appreciate a suggestion for an alternative plugin. Thanks!

**Comment by markmoser** [comment]
This one seems like a great alternative:
https://github.com/Valloric/MatchTagAlways

also:
https://superuser.com/questions/189815/how-to-navigate-between-begin-and-end-html-tag-in-vim

**Comment by 0matgal0** [comment]
Seems like I have found a solution:
https://github.com/gregsexton/MatchTag/pull/42

**Comment by matthewrankin** [comment]
I emailed @gregsexton (original maintainer) and @gishmel (listed maintainer), but didn't receive an answer from either, so I'm assuming this repository is unmaintained/abandoned. Therefore, I have created a new repository (https://github.com/matchtags/MatchTags) forked from this one with the solution from @0matgal0 merged into main. I would like to have multiple maintainers, and am willing to hand it off to someone else as I am not a Vimscript expert.

**Comment by gishmel** [comment]
Sorry for the late reply; I am the current maintainer but I too am no
vimscript expert. I will happily apply the patch if you have verified it
works better with the new version and have some sanity testing done to
ensure the solution works across OS. I will happily test on Mac and Linux
as these are two OS which I have easy access to. Sorry again have been a
bit busy at work; let me know your thoughts and how you would like to
proceed. Have a great day!

Regards,
Luke Greenleaf

**Comment by gishmel** [comment]
Have merged the fix into the repository. Thanks for your help!
